### ISSUE TITLE
Problem with makefile

### ISSUE THREAD

**Issue by BugliL** [su8/kb-layout#1]
While I was trying to make I got this errors
`cc -Wall -Wextra -O2 -lX11 -o kb-layout main.c`

> /tmp/cclgM0CJ.o: In function `main':
> main.c:(.text.startup+0x19): undefined reference to `XOpenDisplay'
> main.c:(.text.startup+0x31): undefined reference to `XkbGetState'
> main.c:(.text.startup+0x43): undefined reference to `XkbGetKeyboard'
> main.c:(.text.startup+0x5b): undefined reference to `XGetAtomName'
> main.c:(.text.startup+0x79): undefined reference to `XFree'
> main.c:(.text.startup+0x81): undefined reference to `XCloseDisplay'
> collect2: error: ld returned 1 exit status
> Makefile:8: recipe for target 'all' failed
> make: *** [all] Error 1
> 

I solved this issue by changing the makefile like this
`$(CC) $(CFLAGS) -o $(PACKAGE) $(PROG) $(LDFLAGS)`
so it runs
`cc -Wall -Wextra -O2 -o kb-layout main.c -lX11`

**Comment by su8** [comment]
Thank you.
